baseURL = "https://debruyn.dev/"
languageCode = "en-us"
title = "Sam Debruyn"
theme = "hugo-goa"
googleAnalytics = "UA-51718684-1"
pygmentsCodeFences = true
pygmentsUseClasses = false
enableGitInfo = true
author = "Sam Debruyn"
enableRobotsTXT = true
pygmentsStyle = "monokai"

[permalinks]
    blog = "/:year/:title/"
    addendum = "/addendum/:year/:title/"

[params]
    author = "Sam Debruyn"
    intro = "Cloud Data Solution Architect"
    description = "Specialized in Microsoft Azure & modern data stack. Public speaker & meetup organizer. FOSS contributor. Currently tech lead data & cloud at [dataroots](https://dataroots.io/)."
    authorimage = "avatar_crop.jpg"
    dateformat = "Jan 2, 2006"

[params.meta]
    description = "Sam Debruyn - Cloud Data Solution architect specialized in Azure, dbt, Terraform, data engineering, cloud engineering"
    keywords = "azure,data,dbt,tech lead,cloud engineer,data engineer"

[params.extra]
    poweredby = false
    socialmarkup = true
    rss = false
    displayrssicon = false

[params.social]
    github = "sdebruyn"
    twitter = "S_Debruyn"
    linkedin = "samueldebruyn"
    stackoverflow = "1592358"
    meetup = "186807757"
    credly = "debruyn"
    accredible = "debruyn"

[[menu.main]]
    name = "about"
    url = "/about/"
    weight = 100
[[menu.main]]
    name = "blog"
    url = "/blog/"
    weight = 200
[[menu.main]]
    name = "public speaking & meetups"
    url = "/tags/speaking/"
    weight = 200
[[menu.main]]
    name = "dataroots blog"
    url = "https://dataroots.io/research/contributions/"
    weight = 999
