baseURL = "https://debruyn.dev/"
languageCode = "en-us"
title = "Sam Debruyn"
theme = "hugo-goa"
googleAnalytics = "UA-51718684-1"
pygmentsCodeFences = true
pygmentsUseClasses = false
enableGitInfo = true
author = "Sam Debruyn"
enableRobotsTXT = true
pygmentsStyle = "monokai"

[permalinks]
    blog = "/:year/:title/"
    addendum = "/addendum/:year/:title/"

[params]
    author = "Sam Debruyn"
    intro = "🚜 data engineer"
    authorimage = "avatar_crop.jpg"
    dateformat = "Jan 2, 2006"

[params.meta]
    description = "Sam Debruyn"
    keywords = "data engineer,developer,portfolio,blog,cloud,cloud native"

[params.extra]
    poweredby = false
    socialmarkup = true

[params.social]
    github = "sdebruyn"
    twitter = "S_Debruyn"
    linkedin = "samueldebruyn"

[[menu.main]]
    name = "about"
    weight = 100
    url = "/about/"
[[menu.main]]
    name = "blog"
    weight = 200
    url = "/blog/"
