baseURL = "https://www.chipsncookies.com/"
languageCode = "en-us"
title = "Chips & Cookies"
theme = "hugo-goa"
googleAnalytics = "UA-51718684-1"
pygmentsCodeFences = true
pygmentsUseClasses = true
enableGitInfo = true
author = "Sam Debruyn"
enableRobotsTXT = true

[permalinks]
    blog = "/:year/:title/"
    addendum = "/addendum/:year/:title/"

[params]
    author = "Chips & Cookies"
    intro = "all the platforms, all the apps"
    description = "Sam Debruyn is a <a href=\"http://www.xamarin.com\" target=\"_blank\">Xamarin</a> mobile app developer & technical lead at <a href=\"http://www.3factr.be\" target=\"_blank\">3factr</a>"
    authorimage = "avatar_crop.jpg"
    dateformat = "Jan 2, 2006"

[params.meta]
    description = "Chips & Cookies by Sam Debruyn"
    keywords = "xamarin,developer,portfolio,blog,mobile,apps,app"

[params.extra]
    hightlightjs = true
    copyright = "&copy; Sam Debruyn 2013-2018. All rights reserved."
    poweredby = false

[params.social]
    github = "SamuelDebruyn"
    twitter = "SamuelDebruyn"
    stackoverflow = "1592358"
    email = "s@muel.be"

[[menu.main]]
    name = "about"
    weight = 100
    url = "/about/"
[[menu.main]]
    name = "blog"
    weight = 200
    url = "/blog/"