baseURL = "https://debruyn.dev/"
languageCode = "en-us"
title = "Sam Debruyn"
theme = "hugo-goa"
googleAnalytics = "UA-51718684-1"
pygmentsCodeFences = true
pygmentsUseClasses = false
enableGitInfo = true
author = "Sam Debruyn"
enableRobotsTXT = true
pygmentsStyle = "monokai"

[permalinks]
    blog = "/:year/:title/"
    addendum = "/addendum/:year/:title/"

[params]
    author = "Sam Debruyn"
    intro = "all the platforms, all the apps"
    description = "Sam Debruyn is a <a href=\"https://www.xamarin.com\" target=\"_blank\">Xamarin</a> mobile app developer & technical lead at <a href=\"http://3factr.be\" target=\"_blank\">3factr</a>.<br/>Sam develops cross-platform mobile apps using <a href=\"https://flutter.dev\" target=\"_blank\">Flutter</a> or <a href=\"https://www.xamarin.com\" target=\"_blank\">Xamarin</a>.<br/><br/><a href=\"https://university.xamarin.com/certification?q=samuel.debruyn@3factr.be#verify\" target=\"_blank\"><img class=\"xcert\" src=\"img/xamcert.png\" /></a>"
    authorimage = "avatar_crop.jpg"
    dateformat = "Jan 2, 2006"

[params.meta]
    description = "Sam Debruyn"
    keywords = "xamarin,flutter,developer,portfolio,blog,mobile,apps,app,cross-platform"

[params.extra]
    copyright = "&copy; Sam Debruyn 2013-2019. All rights reserved."
    poweredby = false
    socialmarkup = true

[params.social]
    github = "sdebruyn"
    twitter = "S_Debruyn"
    stackoverflow = "1592358"
    linkedin = "samueldebruyn"

[[menu.main]]
    name = "about"
    weight = 100
    url = "/about/"
[[menu.main]]
    name = "blog"
    weight = 200
    url = "/blog/"
