baseURL = "https://debruyn.dev/"
languageCode = "en-us"
title = "Sam Debruyn"
theme = "hugo-goa"
googleAnalytics = "G-TG97G5541B"
pygmentsCodeFences = true
pygmentsUseClasses = false
enableGitInfo = true
author = "Sam Debruyn"
enableRobotsTXT = true
pygmentsStyle = "monokai"
buildFuture = true

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[permalinks]
    blog = "/:year/:title/"
    addendum = "/addendum/:year/:title/"

[params]
    author = "Sam Debruyn"
    intro = "Cloud Data Solution Architect"
    description = "Specialized in Microsoft Azure & modern data stack. Public speaker & meetup organizer. FOSS contributor. Currently tech lead data & cloud at [dataroots](https://dataroots.io/)."
    authorimage = "avatar_crop.jpg"
    dateformat = "Jan 2, 2006"

[params.meta]
    description = "Sam Debruyn - Cloud Data Solution Architect specialized in Microsoft Azure & modern data stack."
    keywords = "azure,data,dbt,tech lead,cloud engineer,data engineer"

[params.extra]
    poweredby = false
    socialmarkup = true
    rss = false
    displayrssicon = false

[params.social]
    github = "sdebruyn"
    twitter = "S_Debruyn"
    linkedin = "samueldebruyn"
    stackoverflow = "1592358"
    meetup = "186807757"
    credly = "debruyn"
    accredible = "debruyn"

[[menu.main]]
    name = "about Sam"
    url = "/about/"
    weight = 100
[[menu.main]]
    name = "blog"
    url = "/blog/"
    weight = 400
[[menu.main]]
    name = "public speaking & meetups"
    url = "/speaking/"
    weight = 300
[[menu.main]]
    name = "open source contributions"
    url = "https://github.com/pulls?q=is%3Aclosed+is%3Apr+author%3Asdebruyn"
    weight = 200
[[menu.main]]
    name = "dataroots blog"
    url = "https://dataroots.io/research/contributions/"
    weight = 999
