---
label: default
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: 
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
pages:
- content/blog/moving-from-microsoft-work-to-personal-account.md
- content/blog/one-size-fits-all-mobile-app-frameworks-.md
